import { Log } from "./log"

export const LOGS: Log[] = [
    {id: 0, logdetail: "2021-06-18 17:40:54,727 - INFO - You may use a KEYWORD to filter a line!"},
    {id: 1, logdetail: "2021-06-18 17:40:54,727 - INFO - You may use a KEYWORD to be highlighted in a line!"},
    {id: 2, logdetail: "2021-06-18 17:40:54,728 - DEBUG - This is a sample debug log and generated by C:\Programming\flask-service-webservice\services\service1.py for the purpose of simulating a service."},
    {id: 3, logdetail: "2021-06-18 17:40:55,411 - INFO - This is a sample info log and generated by C:\Programming\flask-service-webservice\services\service1.py for the purpose of simulating a service."},
    {id: 4, logdetail: "2021-06-18 17:40:55,411 - INFO - You may use a KEYWORD to filter a line!"},
    {id: 5, logdetail: "2021-06-18 17:40:55,412 - INFO - You may use a KEYWORD to be highlighted in a line!"},
    {id: 6, logdetail: "2021-06-18 17:40:55,412 - DEBUG - This is a sample debug log and generated by C:\Programming\flask-service-webservice\services\service1.py for the purpose of simulating a service."},
    {id: 7, logdetail: "2021-06-18 17:40:55,815 - INFO - This is a sample info log and generated by C:\Programming\flask-service-webservice\services\service1.py for the purpose of simulating a service."},
    {id: 8, logdetail: "2021-06-18 17:40:55,815 - INFO - You may use a KEYWORD to filter a line!"},
    {id: 9, logdetail: "2021-06-18 17:40:55,816 - INFO - You may use a KEYWORD to be highlighted in a line!"},
    {id: 10, logdetail: "2021-06-18 17:40:55,816 - DEBUG - This is a sample debug log and generated by C:\Programming\flask-service-webservice\services\service1.py for the purpose of simulating a service"},
    {id: 11, logdetail: "2021-06-18 17:40:55,877 - INFO - This is a sample info log and generated by C:\Programming\flask-service-webservice\services\service1.py for the purpose of simulating a service"},
    {id: 12, logdetail: "2021-06-18 17:40:55,877 - INFO - You may use a KEYWORD to filter a line!"},
]